Repository codersforcauses/wajo, pull requests merged in 2024-12, with the labels that each got.

#8 Issue 7 Leaderboard Page
  client/package-lock.json
  client/package.json
  client/src/components/ui/button.tsx
  client/src/components/ui/manager/leaderboard-list.tsx
  client/src/components/ui/search.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/table.tsx
  client/src/hooks/use-fetch-data.ts
  client/src/pages/_app.tsx
  client/src/pages/manager/leaderboard.tsx
  client/src/types/leaderboard.ts
  server/api/manager/__init__.py
  server/api/manager/admin.py
  server/api/manager/apps.py
  server/api/manager/migrations/__init__.py
  server/api/manager/models.py
  server/api/manager/serializers.py
  server/api/manager/urls.py
  server/api/manager/views.py
  server/api/settings.py
  server/api/urls.py
Labels: backend, enhancement, frontend

#23 Add project styling guide and best practices
  client/style-guide.md
Labels: documentation

#25 refactor: rename manager to leaderboard module, add mock API responses
  client/src/components/ui/leaderboard/leaderboard-list.tsx
  client/src/components/ui/search.tsx
  client/src/lib/api.ts
  client/src/pages/api/healthcheck/ping.ts
  client/src/pages/api/leaderboard/list.ts
  client/src/pages/leaderboard/index.tsx
  server/api/leaderboard/__init__.py
  server/api/leaderboard/admin.py
  server/api/leaderboard/apps.py
  server/api/leaderboard/migrations/__init__.py
  server/api/leaderboard/models.py
  server/api/leaderboard/serializers.py
  server/api/leaderboard/urls.py
  server/api/leaderboard/views.py
  server/api/settings.py
  server/api/urls.py
Labels: enhancement, frontend

#26 Issue 22 Tailwind and global styles
  client/package-lock.json
  client/src/pages/index.tsx
  client/src/styles/globals.css
  client/tailwind.config.ts
Labels: enhancement, frontend, component
