Repository codersforcauses/wajo, pull requests merged in 2025-01, with the labels that each got.

#31 Issue 11 create login modal
  client/package-lock.json
  client/package.json
  client/src/components/ui/dialog.tsx
  client/src/components/ui/form.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/label.tsx
  client/src/components/ui/search.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/sonner.tsx
  client/src/components/ui/table.tsx
  client/src/components/ui/user/login-modal.tsx
  client/src/context/auth-provider.tsx
  client/src/hooks/use-fetch-data.ts
  client/src/hooks/use-post-data.ts
  client/src/pages/_app.tsx
  client/src/pages/api/auth/token.tsx
  client/src/pages/index.tsx
  client/src/store/token-store.tsx
  client/src/types/globals.d.ts
  client/src/types/user.ts
Labels: enhancement, frontend, component

#29 Issue 12 create input field with math jax rendering
  client/package-lock.json
  client/package.json
  client/src/components/ui/button.tsx
  client/src/components/ui/math-input.tsx
  client/src/pages/api/render-tikz.ts
  client/src/pages/showcase.tsx
  client/tsconfig.json
Labels: frontend, component

#41 Issue 39 sidebar role based display
  client/package-lock.json
  client/package.json
  client/src/components/ui/app-sidebar.tsx
  client/src/components/ui/collapsible.tsx
  client/src/components/ui/separator.tsx
  client/src/components/ui/sheet.tsx
  client/src/components/ui/sidebar.tsx
  client/src/components/ui/skeleton.tsx
  client/src/components/ui/tooltip.tsx
  client/src/hooks/use-mobile.tsx
  client/src/pages/_app.tsx
  client/src/styles/globals.css
  client/src/types/app-sidebar.ts
  client/src/types/user.ts
  client/tailwind.config.ts
  client/tsconfig.json
Labels: enhancement, frontend, component

#33 Issue 2 Fully Responsive Navbar
  client/package-lock.json
  client/package.json
  client/public/wajo_white.svg
  client/src/components/layout.tsx
  client/src/components/navbar.tsx
  client/src/components/sidebar-layout.tsx
  client/src/components/ui/app-sidebar.tsx
  client/src/components/ui/mobilenav.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/question/index.tsx
  client/src/styles/globals.css
  client/src/styles/modules/navbar.module.css
  client/src/types/app-sidebar.ts
  client/src/types/svg.d.ts
  client/tailwind.config.ts
  client/tsconfig.json
  server/poetry.lock
Labels: enhancement, frontend, component

#48 Implement login verification with `rest_framework_simplejwt`
  server/api/auth/__init__.py
  server/api/auth/admin.py
  server/api/auth/apps.py
  server/api/auth/migrations/__init__.py
  server/api/auth/models.py
  server/api/auth/tests.py
  server/api/auth/urls.py
  server/api/auth/views.py
  server/api/settings.py
  server/api/urls.py
  server/poetry.lock
  server/pyproject.toml
Labels: backend, enhancement

#66 Issue 62 user management components admin dashboard
  client/.env.example
  client/package-lock.json
  client/src/components/layout.tsx
  client/src/components/navbar.tsx
  client/src/components/sidebar-layout.tsx
  client/src/components/sidebar.tsx
  client/src/components/ui/Leaderboard/leaderboard-list.tsx
  client/src/components/ui/Question/data-grid.tsx
  client/src/components/ui/Users/data-grid.tsx
  client/src/components/ui/Users/data-table-form.tsx
  client/src/components/ui/Users/login-modal.tsx
  client/src/components/ui/Users/school-data-grid.tsx
  client/src/components/ui/Users/school-data-table-form.tsx
  client/src/components/ui/Users/select-school.tsx
  client/src/components/ui/Users/team-data-grid.tsx
  client/src/components/ui/Users/team-data-table-form.tsx
  client/src/components/ui/app-sidebar.tsx
  client/src/components/ui/loading.tsx
  client/src/components/ui/mobilenav.tsx
  client/src/components/ui/select-role.tsx
  client/src/components/ui/sidebar.tsx
  client/src/lib/api.ts
  client/src/pages/_app.tsx
  client/src/pages/api/users/index.ts
  client/src/pages/api/users/me.ts
  client/src/pages/api/users/school.ts
  client/src/pages/api/users/team.ts
  client/src/pages/index.tsx
  client/src/pages/leaderboard/index.tsx
  client/src/pages/question/index.tsx
  client/src/pages/users/create.tsx
  client/src/pages/users/create_school.tsx
  client/src/pages/users/create_team.tsx
  client/src/pages/users/index.tsx
  client/src/pages/users/school.tsx
  client/src/pages/users/team.tsx
  client/src/styles/globals.css
  client/src/types/app-sidebar.ts
  client/src/types/data-grid.ts
  client/src/types/question.ts
  client/src/types/school.ts
  client/src/types/team.ts
  client/src/types/user.ts
Labels: frontend, component

#81 Issue 64 create landing page
  client/public/sponsor-logos/Casio.svg
  client/public/sponsor-logos/DoE.svg
  client/public/sponsor-logos/ECU.svg
  client/public/sponsor-logos/MAWA.svg
  client/public/sponsor-logos/Murdoch.svg
  client/public/sponsor-logos/New-Edition.svg
  client/public/sponsor-logos/UWA.svg
  client/src/components/layout.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/footer.tsx
  client/src/components/ui/sponsor.tsx
  client/src/pages/index.tsx
  client/src/styles/globals.css
  client/tailwind.config.ts
Labels: frontend

#63 Issue 61 add question preview modal component
  client/package-lock.json
  client/package.json
  client/src/components/ui/Question/data-grid.tsx
  client/src/components/ui/Question/preview-modal.tsx
  client/src/components/ui/pagination.tsx
  client/src/pages/api/question/list.ts
  client/src/pages/question/create.tsx
  client/src/pages/question/index.tsx
  client/src/types/question.ts
Labels: frontend, component

#69 Issue 43 API endpoint for leaderboard - Individual and Team Filters (with tests)
  server/api/auth/tests.py
  server/api/leaderboard/models.py
  server/api/leaderboard/serializers.py
  server/api/leaderboard/tests.py
  server/api/leaderboard/urls.py
  server/api/leaderboard/views.py
  server/api/question/models.py
  server/api/question/serializers.py
  server/api/quiz/migrations/0006_alter_questionattempt_answer_student_and_more.py
  server/api/quiz/migrations/0007_alter_quizattempt_state_and_more.py
  server/api/quiz/migrations/0008_merge_20250125_1627.py
  server/api/quiz/migrations/0009_quizattempt_team.py
  server/api/quiz/models.py
  server/api/settings.py
  server/api/team/admin.py
  server/api/team/migrations/0002_remove_team_grades_teammember_team_students_and_more.py
  server/api/team/migrations/0003_alter_teammember_student_alter_teammember_team.py
  server/api/team/models.py
  server/api/team/serializers.py
  server/api/team/tests.py
  server/api/team/urls.py
  server/api/team/views.py
  server/api/urls.py
  server/api/users/admin.py
  server/api/users/migrations/0002_school_is_country_school_type_student_attendent_year.py
  server/api/users/models.py
  server/api/users/tests.py
Labels: backend

#85 Issue 84 Reconnect Client-Server and Role field JWT Payload
  client/src/components/layout.tsx
  client/src/lib/api.ts
  client/src/pages/question/index.tsx
  client/src/types/globals.d.ts
  server/api/auth/serializers.py
  server/api/auth/urls.py
  server/api/auth/views.py
Labels: backend, enhancement, frontend

#98 Fix add random student id as the login username
  server/api/question/serializers.py
  server/api/question/tests.py
  server/api/question/urls.py
  server/api/quiz/models.py
  server/api/quiz/views.py
  server/api/users/migrations/0004_school_abbreviation.py
  server/api/users/models.py
  server/api/users/serializers.py
  server/api/users/tests.py
  server/api/users/views.py
Labels: backend, database

#99 Issue 95 Align Client-Server Endpoints
  client/src/components/ui/Question/data-grid.tsx
  client/src/components/ui/Test/competition-data-grid.tsx
  client/src/components/ui/Test/practice-data-grid.tsx
  client/src/components/ui/Test/question-block-manager.tsx
  client/src/components/ui/Users/school-data-grid.tsx
  client/src/components/ui/Users/school-data-table-form.tsx
  client/src/components/ui/Users/select-school.tsx
  client/src/components/ui/Users/team-data-grid.tsx
  client/src/pages/api/question/list.ts
  client/src/pages/api/test/practices.ts
  client/src/pages/api/users/school.ts
  client/src/pages/api/users/team.ts
  client/src/pages/question/index.tsx
  client/src/pages/test/competition/index.tsx
  client/src/pages/test/index.tsx
  client/src/pages/test/leaderboard/index.tsx
  client/src/pages/test/leaderboard/insight.tsx
  client/src/pages/test/leaderboard/ranking.tsx
  client/src/pages/users/index.tsx
  client/src/pages/users/school.tsx
  client/src/pages/users/team.tsx
  client/src/types/leaderboard.ts
  client/src/types/practice.ts
  client/src/types/question.ts
  client/src/types/quiz.ts
  client/src/types/school.ts
  client/src/types/team.ts
  client/src/types/user.ts
Labels: enhancement, frontend

#104 103 wrap school id info and some teacher or student id into the jwt token paypload
  server/api/auth/serializers.py
  server/api/auth/urls.py
  server/api/auth/views.py
  server/api/users/serializers.py
  server/api/users/views.py
Labels: backend, bug, database
