Repository codersforcauses/wajo, pull requests merged in 2025-02, with the labels that each got.

#108 Issue 107 rebuild for the issue 77
  server/api/users/admin.py
  server/api/users/models.py
  server/api/users/serializers.py
  server/api/users/views.py
Labels: backend

#132 Issue 120 create question management admin
  client/package-lock.json
  client/package.json
  client/src/components/ui/Question/preview-modal.tsx
  client/src/components/ui/scroll-area.tsx
  client/src/pages/question/[id].tsx
  client/src/pages/question/create.tsx
  client/src/types/question.ts
Labels: frontend

#136 Issue 135 - Hotfix Invalid Image Dimensions & Update Bug
  client/src/components/ui/Question/preview-modal.tsx
  client/src/pages/question/[id].tsx
  client/src/pages/question/create.tsx
Labels: bug, frontend, component

#142 Issue 140 front end role permission validation
  client/src/components/layout.tsx
  client/src/components/navbar.tsx
  client/src/components/sidebar.tsx
  client/src/components/ui/Question/add-modal.tsx
  client/src/components/ui/Question/data-grid.tsx
  client/src/components/ui/Question/retry-modal.tsx
  client/src/components/ui/Team/data-grid.tsx
  client/src/components/ui/Users/data-grid.tsx
  client/src/components/ui/Users/login-modal.tsx
  client/src/components/ui/Users/select-year.tsx
  client/src/components/ui/Users/team-data-grid.tsx
  client/src/components/ui/app-sidebar.tsx
  client/src/components/ui/mobilenav.tsx
  client/src/components/ui/sponsor.tsx
  client/src/context/auth-provider.tsx
  client/src/lib/api.ts
  client/src/pages/401.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/users/index.ts
  client/src/pages/dashboard/index.tsx
  client/src/pages/dashboard/question/[id].tsx
  client/src/pages/dashboard/question/category/[id].tsx
  client/src/pages/dashboard/question/category/create.tsx
  client/src/pages/dashboard/question/category/index.tsx
  client/src/pages/dashboard/question/create.tsx
  client/src/pages/dashboard/question/index.tsx
  client/src/pages/dashboard/test/[id].tsx
  client/src/pages/dashboard/test/competition/[id].tsx
  client/src/pages/dashboard/test/competition/create.tsx
  client/src/pages/dashboard/test/competition/index.tsx
  client/src/pages/dashboard/test/create.tsx
  client/src/pages/dashboard/test/index.tsx
  client/src/pages/dashboard/users/[id].tsx
  client/src/pages/dashboard/users/index.tsx
  client/src/pages/dashboard/users/school/[id].tsx
  client/src/pages/dashboard/users/school/create.tsx
  client/src/pages/dashboard/users/school/index.tsx
  client/src/pages/dashboard/users/staffs/create.tsx
  client/src/pages/dashboard/users/staffs/index.tsx
  client/src/pages/dashboard/users/students/create.tsx
  client/src/pages/dashboard/users/students/index.tsx
  client/src/pages/dashboard/users/teachers/create.tsx
  client/src/pages/dashboard/users/teachers/index.tsx
  client/src/pages/dashboard/users/team/[id].tsx
  client/src/pages/dashboard/users/team/create.tsx
  client/src/pages/dashboard/users/team/index.tsx
  client/src/pages/index.tsx
  client/src/pages/team/[teamId].tsx
  client/src/pages/team/create.tsx
  client/src/types/app-sidebar.ts
  client/src/types/globals.d.ts
  client/src/types/user.ts
Labels: bug, enhancement, frontend
